Repository rhinosstuff/Book-Finder, pull requests merged in 2024-05, with the labels that each got.

#7 modernized MIT License to meet compliance changes to Industry Standards.
  LICENSE
Labels: documentation

#9 Lucky
  assets/js/lucky.js
Labels: enhancement

#12 Lucky
  assets/js/lucky.js
Labels: enhancement

#15 Added Movies API, Updated Books Api
  assets/js/googleBooksAPI.js
  assets/js/movieAPI.js
  testBooks.html
Labels: enhancement

#16 Added Nav bar, Header, Feeling lucky, & footer
  assets/images/Bookshelf_Textbook_Stock.jpg
  assets/images/High_Class_Bookshelf.jpg
  index.html
  testBooks.html
Labels: enhancement

#18 Generating Ideas
  .vscode/settings.json
  assets/js/googleBooksAPI.js
  assets/js/script.js
  index copy.html
Labels: documentation, enhancement

#20 Css styling
  assets/Fonts/CedarvilleCursive-Regular.ttf
  assets/css/style.css
  assets/js/googleBooksAPI.js
  assets/js/movieAPI.js
Labels: help wanted

#23 Separated the JS files
  assets/js/bookAPI.js
  assets/js/bookDisplay.js
  assets/js/movieAPI.js
  assets/js/movieDisplay.js
  assets/js/script.js
  index copy.html
Labels: enhancement

#24 Working on book API filters
  assets/js/bookAPI.js
  assets/js/bookDisplay.js
  assets/js/movieDisplay.js
  index copy.html
Labels: enhancement

#25 Cleaned Code in both API
  assets/js/bookAPI.js
  assets/js/bookDisplay.js
  assets/js/movieAPI.js
  assets/js/movieDisplay.js
  index copy.html
Labels: enhancement

#26 Html setup
  assets/Fonts/CedarvilleCursive-Regular.ttf
  assets/css/style.css
  assets/images/High_Class_Bookshelf.jpg
  index.html
Labels: enhancement

#27 merged our index.html together
  assets/js/lucky.js
  index copy.html
  index.html
  testBooks.html
Labels: enhancement

#28 Updated CSS & HTML
  assets/css/style.css
  index.html
Labels: enhancement

#31 made it so the movie modal is interactive
  assets/js/bookAPI.js
  assets/js/bookDisplay.js
  assets/js/movieAPI.js
  assets/js/movieDisplay.js
  index.html
Labels: enhancement
